package com.redhat.servicecatlog.apprvoal;

import com.redhat.servicecatlog.RequestItem;
import com.redhat.servicecatlog.ServiceRequest;

rule "BudgetQuota"
  ruleflow-group "quota_group"
  when
    request : ServiceRequest(getItem().getRequestedBudget() + getItem().getUsedBudget() > getItem().getAllocatedBudget())
  then
    modify(request) {setQuotaStatus("Failed")};
    System.out.println("fired rule " + kcontext.getRule().getName());
end


