package com.redhat.servicecatlog.apprvoal;

import com.redhat.servicecatlog.RequestItem;
import com.redhat.servicecatlog.ServiceRequest;

rule "CpuQuota"
  ruleflow-group "quota_group"
  when
    request : ServiceRequest(getItem().getRequestedCpus() + getItem().getUsedCpus() > getItem().getAllocatedCpus())
  then
    modify(request) {setQuotaStatus("Failed")};
    System.out.println("fired rule " + kcontext.getRule().getName());
end


