package com.redhat.servicecatlog.apprvoal;

import com.redhat.servicecatlog.RequestItem;
import com.redhat.servicecatlog.ServiceRequest;

rule "MemoryQuota"
  ruleflow-group "quota_group"
  when
    request : ServiceRequest(item.requestedMemories + item.usedMemories > item.allocatedMemories)
  then
    request.setQuotaStatus("Failed");
        
    String allocatedS = request.getItem().getAllocatedMemories() + "GB";
    int shortage = request.getItem().getAllocatedMemories() - 
                   request.getItem().getRequestedMemories() -
                   request.getItem().getUsedMemories();
    String shortageS = shortage + "G";
    
    String msg = String.format("Memory has gone over allocated %s by %s", allocatedS, shortageS);
    request.setQuotaErrorMsg(msg);
    
    System.out.println("fired rule " + kcontext.getRule().getName());
end


