package com.redhat.servicecatlog.apprvoal;

import com.redhat.servicecatlog.RequestItem;
import com.redhat.servicecatlog.ServiceRequest;

rule "ServiceApproval"
  ruleflow-group "approval_group"
  when
    request : ServiceRequest(approvalStatus != "Manual" && (userLabel=="Requires-Approval"))
  then
    modify(request) {setApprovalStatus("Manual")};
    System.out.println("fired rule " + kcontext.getRule().getName());
end
