package com.redhat.servicecatlog.apprvoal;

import com.redhat.servicecatlog.RequestItem;
import com.redhat.servicecatlog.ServiceRequest;

rule "StorageQuota"
  ruleflow-group "quota_group"
  when
    request : ServiceRequest(getItem().getRequestedStorages() + getItem().getUsedStorages() > getItem().getAllocatedStorages())
  then
    modify(request) {setQuotaStatus("Failed")};
    System.out.println("fired rule " + kcontext.getRule().getName());
end
