package com.redhat.servicecatlog.apprvoal;

import com.redhat.servicecatlog.RequestItem;
import com.redhat.servicecatlog.ServiceRequest;

rule "VmQuota"
  ruleflow-group "quota_group"
  when
    request : ServiceRequest(getItem().getRequestedVms() + getItem().getUsedVms() > getItem().getAllocatedVms())
  then
    modify(request) {setQuotaStatus("Failed")};
    System.out.println("fired rule " + kcontext.getRule().getName());
end


