package com.redhat.servicecatlog;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Approver implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Slack URL")
   private java.lang.String slackAddress;
   @org.kie.api.definition.type.Label("Name of Approver")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("Approval Status")
   private java.lang.String status;

   @org.kie.api.definition.type.Label(value = "When it is notified")
   private java.lang.String notifyTime;

   @org.kie.api.definition.type.Label(value = "When it is approved")
   private java.lang.String actionTime;
   
   private java.lang.String approvalId;

   public Approver()
   {
   }

   public java.lang.String getSlackAddress()
   {
      return this.slackAddress;
   }

   public void setSlackAddress(java.lang.String slackAddress)
   {
      this.slackAddress = slackAddress;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String getNotifyTime()
   {
      return this.notifyTime;
   }

   public void setNotifyTime(java.lang.String notifyTime)
   {
      this.notifyTime = notifyTime;
   }

   public java.lang.String getActionTime()
   {
      return this.actionTime;
   }

   public void setActionTime(java.lang.String actionTime)
   {
      this.actionTime = actionTime;
   }

   public Approver(java.lang.String slackAddress, java.lang.String name,
         java.lang.String status, java.lang.String notifyTime,
         java.lang.String actionTime)
   {
      this.slackAddress = slackAddress;
      this.name = name;
      this.status = status;
      this.notifyTime = notifyTime;
      this.actionTime = actionTime;
   }
}