package com.redhat.servicecatlog;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Approver implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Slack URL")
   private java.lang.String slackAddress;
   @org.kie.api.definition.type.Label(value = "Name of Approver")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Approval Status")
   private java.lang.String status;

   public Approver()
   {
   }

   public java.lang.String getSlackAddress()
   {
      return this.slackAddress;
   }

   public void setSlackAddress(java.lang.String slackAddress)
   {
      this.slackAddress = slackAddress;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public Approver(java.lang.String name, java.lang.String slackAddress, 
         java.lang.String status)
   {
      this.slackAddress = slackAddress;
      this.name = name;
      this.status = status;
   }

}