package com.redhat.servicecatlog;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class RequestItem implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Allocated CPUs")
   private int allocatedCpus;

   @org.kie.api.definition.type.Label(value = "Allocated VMs")
   private int allocatedVms;

   @org.kie.api.definition.type.Label(value = "Allocated Memories in GB")
   private int allocatedMemories;

   @org.kie.api.definition.type.Label(value = "Allocated Budget")
   private double allocatedBudget;

   @org.kie.api.definition.type.Label(value = "Used CPUs")
   private int usedCpus;

   @org.kie.api.definition.type.Label(value = "Allocated Storage in GB")
   private int allocatedStorages;

   @org.kie.api.definition.type.Label(value = "Used VMs")
   private int usedVms;

   @org.kie.api.definition.type.Label(value = "Used Memories in GB")
   private int usedMemories;

   @org.kie.api.definition.type.Label(value = "Used Storage in GB")
   private int usedStorages;

   @org.kie.api.definition.type.Label(value = "Used Budget")
   private double usedBudget;

   @org.kie.api.definition.type.Label(value = "Requested CPUs")
   private int requestedCpus;

   @org.kie.api.definition.type.Label(value = "Requested VMs")
   private int requestedVms;

   @org.kie.api.definition.type.Label(value = "Requested Memory in GB")
   private int requestedMemories;

   @org.kie.api.definition.type.Label(value = "Requested Storage in GB")
   private int requestedStorages;

   @org.kie.api.definition.type.Label(value = "Requested Budget")
   private double requestedBudget;

   public RequestItem()
   {
   }

   public String toString()
   {
	  String cost = java.text.NumberFormat.getCurrencyInstance().format(requestedBudget);
	  return "" + requestedCpus + " cpu, " + requestedMemories + "G memory, " + requestedStorages + "G disk, cost " + cost;		   
   }

   public int getAllocatedCpus()
   {
      return this.allocatedCpus;
   }

   public void setAllocatedCpus(int allocatedCpus)
   {
      this.allocatedCpus = allocatedCpus;
   }

   public int getAllocatedVms()
   {
      return this.allocatedVms;
   }

   public void setAllocatedVms(int allocatedVms)
   {
      this.allocatedVms = allocatedVms;
   }

   public int getAllocatedMemories()
   {
      return this.allocatedMemories;
   }

   public void setAllocatedMemories(int allocatedMemories)
   {
      this.allocatedMemories = allocatedMemories;
   }

   public double getAllocatedBudget()
   {
      return this.allocatedBudget;
   }

   public void setAllocatedBudget(double allocatedBudget)
   {
      this.allocatedBudget = allocatedBudget;
   }

   public int getUsedCpus()
   {
      return this.usedCpus;
   }

   public void setUsedCpus(int usedCpus)
   {
      this.usedCpus = usedCpus;
   }

   public int getAllocatedStorages()
   {
      return this.allocatedStorages;
   }

   public void setAllocatedStorages(int allocatedStorages)
   {
      this.allocatedStorages = allocatedStorages;
   }

   public int getUsedVms()
   {
      return this.usedVms;
   }

   public void setUsedVms(int usedVms)
   {
      this.usedVms = usedVms;
   }

   public int getUsedMemories()
   {
      return this.usedMemories;
   }

   public void setUsedMemories(int usedMemories)
   {
      this.usedMemories = usedMemories;
   }

   public int getUsedStorages()
   {
      return this.usedStorages;
   }

   public void setUsedStorages(int usedStorages)
   {
      this.usedStorages = usedStorages;
   }

   public double getUsedBudget()
   {
      return this.usedBudget;
   }

   public void setUsedBudget(double usedBudget)
   {
      this.usedBudget = usedBudget;
   }

   public int getRequestedCpus()
   {
      return this.requestedCpus;
   }

   public void setRequestedCpus(int requestedCpus)
   {
      this.requestedCpus = requestedCpus;
   }

   public int getRequestedVms()
   {
      return this.requestedVms;
   }

   public void setRequestedVms(int requestedVms)
   {
      this.requestedVms = requestedVms;
   }

   public int getRequestedMemories()
   {
      return this.requestedMemories;
   }

   public void setRequestedMemories(int requestedMemories)
   {
      this.requestedMemories = requestedMemories;
   }

   public int getRequestedStorages()
   {
      return this.requestedStorages;
   }

   public void setRequestedStorages(int requestedStorages)
   {
      this.requestedStorages = requestedStorages;
   }

   public double getRequestedBudget()
   {
      return this.requestedBudget;
   }

   public void setRequestedBudget(double requestedBudget)
   {
      this.requestedBudget = requestedBudget;
   }

   public RequestItem(int allocatedCpus, int allocatedVms, int allocatedMemories,
         double allocatedBudget, int allocatedStorages, int usedCpus, 
         int usedVms, int usedMemories, int usedStorages, double usedBudget,
         int requestedCpus, int requestedVms, int requestedMemories,
         int requestedStorages, double requestedBudget)
   {
      this.allocatedCpus = allocatedCpus;
      this.allocatedVms = allocatedVms;
      this.allocatedMemories = allocatedMemories;
      this.allocatedBudget = allocatedBudget;
      this.usedCpus = usedCpus;
      this.allocatedStorages = allocatedStorages;
      this.usedVms = usedVms;
      this.usedMemories = usedMemories;
      this.usedStorages = usedStorages;
      this.usedBudget = usedBudget;
      this.requestedCpus = requestedCpus;
      this.requestedVms = requestedVms;
      this.requestedMemories = requestedMemories;
      this.requestedStorages = requestedStorages;
      this.requestedBudget = requestedBudget;
   }
}