package com.redhat.servicecatlog;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestItem implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RequestItem() {
    }

}