package com.redhat.servicecatlog;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ServiceRequest")
public class ServiceRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Requestor")
   private java.lang.String requestor;
   @org.kie.api.definition.type.Label("Status")
   private java.lang.String status;

   @org.kie.api.definition.type.Label(value = "Request Item")
   private com.redhat.servicecatlog.RequestItem item;

   public ServiceRequest()
   {
   }

   public java.lang.String getRequestor()
   {
      return this.requestor;
   }

   public void setRequestor(java.lang.String requestor)
   {
      this.requestor = requestor;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public com.redhat.servicecatlog.RequestItem getItem()
   {
      return this.item;
   }

   public void setItem(com.redhat.servicecatlog.RequestItem item)
   {
      this.item = item;
   }

   public ServiceRequest(java.lang.String requestor, java.lang.String status,
         com.redhat.servicecatlog.RequestItem item)
   {
      this.requestor = requestor;
      this.status = status;
      this.item = item;
   }

}