package com.redhat.servicecatlog;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ServiceRequest")
public class ServiceRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Requestor")
   private java.lang.String requestor;
   @org.kie.api.definition.type.Label("Status")
   private java.lang.String status;

   @org.kie.api.definition.type.Label("Request Item")
   private com.redhat.servicecatlog.RequestItem item;

   @org.kie.api.definition.type.Label(value = "Service Catalog Name")
   private java.lang.String serviceName;

   @org.kie.api.definition.type.Label(value = "User Approval Label")
   private java.lang.String userLabel;

   @org.kie.api.definition.type.Label(value = "Project Approval Label")
   private java.lang.String projectLabel;

   @org.kie.api.definition.type.Label(value = "Service Item Approval Label")
   private java.lang.String serviceLabel;

   public ServiceRequest()
   {
   }

   public java.lang.String getRequestor()
   {
      return this.requestor;
   }

   public void setRequestor(java.lang.String requestor)
   {
      this.requestor = requestor;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public com.redhat.servicecatlog.RequestItem getItem()
   {
      return this.item;
   }

   public void setItem(com.redhat.servicecatlog.RequestItem item)
   {
      this.item = item;
   }

   public java.lang.String getServiceName()
   {
      return this.serviceName;
   }

   public void setServiceName(java.lang.String serviceName)
   {
      this.serviceName = serviceName;
   }

   public java.lang.String getUserLabel()
   {
      return this.userLabel;
   }

   public void setUserLabel(java.lang.String userLabel)
   {
      this.userLabel = userLabel;
   }

   public java.lang.String getProjectLabel()
   {
      return this.projectLabel;
   }

   public void setProjectLabel(java.lang.String projectLabel)
   {
      this.projectLabel = projectLabel;
   }

   public java.lang.String getServiceLabel()
   {
      return this.serviceLabel;
   }

   public void setServiceLabel(java.lang.String serviceLabel)
   {
      this.serviceLabel = serviceLabel;
   }

   public ServiceRequest(java.lang.String requestor, java.lang.String status,
         com.redhat.servicecatlog.RequestItem item,
         java.lang.String serviceName, java.lang.String userLabel,
         java.lang.String projectLabel, java.lang.String serviceLabel)
   {
      this.requestor = requestor;
      this.status = status;
      this.item = item;
      this.serviceName = serviceName;
      this.userLabel = userLabel;
      this.projectLabel = projectLabel;
      this.serviceLabel = serviceLabel;
   }

}