package com.redhat.servicecatlog;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Slacker implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SLACKER_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "SLACKER_ID_GENERATOR", sequenceName = "SLACKER_ID_SEQ")
    private java.lang.Long id;

    public Slacker() {
    }
    
    public Slacker(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}