package com.redhat.servicecatlog;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SlackClient implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Slack Web Hook URL")
   private java.lang.String slackAddress;
   @org.kie.api.definition.type.Label(value = "Slack Channel or User")
   private java.lang.String slackChannel;
   @org.kie.api.definition.type.Label(value = "Service Request")
   private com.redhat.servicecatlog.ServiceRequest serviceRequest;

   public SlackClient()
   {
   }

   public java.lang.String getSlackAddress()
   {
      return this.slackAddress;
   }

   public void setSlackAddress(java.lang.String slackAddress)
   {
      this.slackAddress = slackAddress;
   }

   public java.lang.String getSlackChannel()
   {
      return this.slackChannel;
   }

   public void setSlackChannel(java.lang.String slackChannel)
   {
      this.slackChannel = slackChannel;
   }

   public com.redhat.servicecatlog.ServiceRequest getServiceRequest()
   {
      return this.serviceRequest;
   }

   public void setServiceRequest(
         com.redhat.servicecatlog.ServiceRequest serviceRequest)
   {
      this.serviceRequest = serviceRequest;
   }

   public SlackClient(java.lang.String slackAddress,
         java.lang.String slackChannel,
         com.redhat.servicecatlog.ServiceRequest serviceRequest)
   {
      this.slackAddress = slackAddress;
      this.slackChannel = slackChannel;
      this.serviceRequest = serviceRequest;
   }

}