package com.redhat.servicecatlog;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Test implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Abc")
   private com.redhat.servicecatlog.RequestItem abc;

   public Test()
   {
   }

   public com.redhat.servicecatlog.RequestItem getAbc()
   {
      return this.abc;
   }

   public void setAbc(com.redhat.servicecatlog.RequestItem abc)
   {
      this.abc = abc;
   }

   public Test(com.redhat.servicecatlog.RequestItem abc)
   {
      this.abc = abc;
   }

}